CREATE TABLE IF NOT EXISTS outbound_%m%Y (
        agent_id INT UNSIGNED NOT NULL DEFAULT 0,
        mac_src CHAR(17) NOT NULL,
        mac_dst CHAR(17) NOT NULL,
        vlan INT UNSIGNED NOT NULL,
        ip_src VARCHAR(50) NOT NULL,
        ip_dst VARCHAR(50) NOT NULL,
        src_port INT UNSIGNED NOT NULL,
        dst_port INT UNSIGNED NOT NULL,
        ip_proto VARCHAR(20) NOT NULL,
        packets INT UNSIGNED NOT NULL,
        post_nat_ip_dst VARCHAR(50) NOT NULL DEFAULT '',
        post_nat_port_src INT NOT NULL DEFAULT 0,
        post_nat_ip_src VARCHAR(50) NOT NULL DEFAULT '',
        post_nat_port_dst INT NOT NULL DEFAULT 0,
        bytes BIGINT UNSIGNED NOT NULL,
        stamp_inserted DATETIME NOT NULL,
        stamp_updated DATETIME,
        PRIMARY KEY (agent_id, mac_src, mac_dst, vlan, ip_src, ip_dst, src_port, dst_port, ip_proto,
        post_nat_ip_dst, post_nat_ip_src, post_nat_port_dst, post_nat_port_src,
        stamp_inserted)
);
